# -*- coding: utf-8 -*-
"""Tarea 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEV8ouXTDCf0nyc_2Kc1ymZR1QCx42VD
"""

#Problema 3.1
sumPar = 0
sumaImp = 0
cuentaPar = 0
num = 0
i=1
while i <= 270:
    num = i 
    if num > 0:
        if  num%2!= 0:
            sumPar = sumPar + cuentaPar 
            cuentaPar = cuentaPar + 1
        else: sumaImp=sumaImp+num
    i=i+1
promedioPar = sumPar / cuentaPar
print(promedioPar, sumPar)

#Problema 3.2
BAND, SUMSER, I = "T",0.1, 2
while I <= 1800:
    SUMSER = SUMSER + 1 
    print(I)
    if BAND == "T":
        BAND = "F"
        I = I + 3
    else:
        BAND = "T"
        I = I + 2
print(SUMSER)

#Problema 3.3
n = int(input("Dame un valor entero: "))
band,serie ='T', 0
i=1
while i<=n:
    if band=='T':
        serie=serie+(1/i)
        band='F'
    else: 
        serie=serie-(1/i)
        band='T'
    i=i+1
print(serie)

#Problema 3.4
nom=0
nominas=[855,760.32,1100.2,614,2600,817.5,1280.3,687,-1]
i=0
while nominas[i] > -1:
    if nominas[i] < 1000:
        nsue=round(nominas[i]*1.15,2)
    else:
        nsue=round(nominas[i]*1.12,2)
    nom=round(nom+nsue,2)
    i=i+1
    print("El sueldo es:", nsue)
print("La nomína es:",nom)